name: release

permissions:
  contents: write

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  Windows_2022_32bit:
    runs-on: windows-2022
    env:
      MSBUILD_PATH: C:\Program Files (x86)\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Configure CMake
        shell: cmd
        run: |
          mkdir build
          cmake -DCMAKE_BUILD_TYPE=Release -S . -B build -A Win32
      - name: Build
        shell: cmd
        run: |
          # https://stackoverflow.com/a/19026241
          cmake --build build --config Release
      - name: Get Exe Hash
        id: hashes
        shell: pwsh
        run: |
          $exe_hash = $(Get-FileHash build/Release/xiloader.exe -Algorithm MD5).hash
          "::set-output name=exe_hash::$($exe_hash)"
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
          files: build/Release/xiloader.exe
          body: |
            MD5: ${{ steps.hashes.outputs.exe_hash }}
          draft: false
          prerelease: false
